# Generated by Django 4.2.14 on 2024-07-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRide', '0002_admin_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
