# Generated by Django 4.2.14 on 2024-07-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRide', '0003_driver_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_id',
            new_name='id',
        ),
    ]
