# Generated by Django 4.2.14 on 2024-07-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRide', '0005_remove_driver_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driving_license_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
