# Generated by Django 4.2.14 on 2024-07-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRide', '0006_driver_driving_license_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='id',
            new_name='driver_id',
        ),
    ]
